# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'GoogleMaps', '= 2.5.0'


  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

end
